info:
  contact: {}
  description: This is an api to show videos
  title: Finpay Task - Video API
  version: "1.0"
paths:
  /admin/apikey:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Get all youtube apikeys from list
      tags:
      - Get APIKeys
    post:
      parameters:
      - description: API key to be added
        in: query
        name: apikey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Add youtube apikey to the list
      tags:
      - Add APIKey
  /video/search:
    get:
      parameters:
      - description: Query term to search
        in: query
        name: query
        required: true
        type: string
      - description: Page number
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Get latest videos by query
      tags:
      - Video Search
swagger: "2.0"
